#!/usr/bin/env python
"""Brain-Even Game."""


from random import randint

import prompt
from brain_games.scripts.brain_games import welcome_user


def is_even(number):
    """Decides the number is even or not.

    Parameters:
        - number (int): generated by random module

    Returns:
        - return string 'yes' or 'no'.

    """
    if number % 2 == 0:
        return 'yes'
    return 'no'


def get_user_answer():
    return prompt.string('Your answer: ')


def get_correct_answer(number):
    return is_even(number)


def is_user_answer_correct(answer, correct_answer):
    if answer == correct_answer:
        print('Correct!')
        return True
    return False


def game_ends(name, correct_answer, answer, count):
    win_answer = ('Congratulations, {0}!'.format(name))
    lose_answer = ("'{2}' is wrong answer ;(. Correct answer was '{1}'.\n"
                   "Let\'s try again, {0}!".format(name, correct_answer, answer))
    if count == 3:
        return win_answer
    elif answer.lower() != correct_answer:
        return lose_answer


def count_attempts(count):
    count += 1
    return count


def main():
    """Do the main start of the "Brain-Even Game"."""
    name = welcome_user()
    print('Answer "yes" if the number is even, otherwise answer "no".')

    count = 0
    while count < 3:
        number = randint(1, 99)
        print('Question: {0}'.format(number))
        answer = get_user_answer()
        correct_answer = get_correct_answer(number)
        if is_user_answer_correct(answer, correct_answer) is True:
            count = count_attempts(count)
        else:
            print(game_ends(name, correct_answer, answer, count))
            break
        print(game_ends(name, correct_answer, answer, count))


if __name__ == '__main__':
    main()
