#!/usr/bin/env python
"""Brain-Even Game."""

from random import randint

import prompt


def is_even(number):
    """Decides the number is even or not.

    Parameters:
        number (int): generated by random module

    Returns:
        - return string 'yes' or 'no'.

    """
    if number % 2 == 0:
        return 'yes'
    return 'no'


def main():
    """Do the main start of the program."""
    # part 1 - weclome user
    print('Welcome to the Brain games!')
    name = prompt.string('May I have your name? ')
    print('Hello, {0}!'.format(name))
    print('Answer "yes" if the number is even, otherwise answer "no".')
    # part 2 - main game
    count_correct_answers = 0
    while count_correct_answers != 3:
        number = randint(1, 99)
        print('Question: {0}'.format(number))
        answer = prompt.string('Your answer: ')
        correct_answer = is_even(number)
        if answer.lower() == correct_answer:
            print('Correct!')
            count_correct_answers += 1
        else:
            break
    # part 3 - ends of the program
    if count_correct_answers == 3:
        print('Congratulations, {0}!'.format(name))
    elif answer.lower() != correct_answer:
        print("'{2}' is wrong answer ;(. Correct answer was '{1}'.\n"
              "Let\'s try again, {0}!".format(name, correct_answer, answer))


if __name__ == '__main__':
    main()
